# Generated by Django 5.2 on 2025-05-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0002_studentstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_line',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='get_group', to='training_center.groupstudent'),
        ),
    ]
