# Generated by Django 5.1.6 on 2025-05-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0003_student_is_line_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
