# Generated by Django 5.1.6 on 2025-05-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_center', '0004_alter_payments_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('online', 'Online')], max_length=50, null=True),
        ),
    ]
